# Generated by Django 3.2.8 on 2021-11-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20211115_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('reply', 'reply'), ('share', 'share'), ('friend_request', 'friend_request'), ('friend_request_accept', 'friend_request_accept'), ('message', 'message')], max_length=30),
        ),
    ]
