# Generated by Django 3.2.8 on 2021-10-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211027_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='author',
        ),
    ]
